# models.py
from .extensions import db

class CaseInfor(db.Model):
    __tablename__ = 'caseinfor'
    caid = db.Column(db.BigInteger, primary_key=True)
    casno = db.Column(db.String(30))
    caifend = db.Column(db.String(1))
    caereason = db.Column(db.String(1000))
    caifupload = db.Column(db.String(1))
    casource = db.Column(db.String(3))
    rcno = db.Column(db.String(30))
    cadate = db.Column(db.Date)
    token = db.Column(db.String(100))
    isObserve = db.Column(db.String(1))
    caDistrict = db.Column(db.String(60))
    caRoad = db.Column(db.String(200))
    caAddr = db.Column(db.String(300))
    caroadDirect = db.Column(db.String(1))
    caroadNum = db.Column(db.BigInteger)
    catype = db.Column(db.String(3))
    cabad = db.Column(db.String(3))
    cabaddegree = db.Column(db.String(3))
    camemo = db.Column(db.String(500))
    cagis_lon = db.Column(db.Numeric(15, 10))
    cagis_lat = db.Column(db.Numeric(15, 10))
    caimg_1 = db.Column(db.String(100))
    caimg_2 = db.Column(db.String(100))
    caimg_3 = db.Column(db.String(100))
    adddate = db.Column(db.DateTime)
    addid = db.Column(db.String(20))
    addname = db.Column(db.String(100))
    cafrom = db.Column(db.String(1))
    cafromno = db.Column(db.String(30))
    cimgsuc = db.Column(db.String(1))
    return_ID = db.Column(db.String(30))
    failreason = db.Column(db.String(4000))
    bmodid = db.Column(db.String(20))
    bmoddate = db.Column(db.DateTime)
    carno = db.Column(db.String(10))
    castatus = db.Column(db.String(1))
    calength = db.Column(db.String(40))
    cawidth = db.Column(db.String(40))
    caarea = db.Column(db.String(40))
    caimg_4 = db.Column(db.String(100))
    caimg_5 = db.Column(db.String(100))
    catime = db.Column(db.DateTime)

class ReportData(db.Model):
    __tablename__ = 'reportdata'
    rid = db.Column(db.BigInteger, primary_key=True)
    rtype = db.Column(db.String(1))
    rdate = db.Column(db.Date)
    rfile_exc1 = db.Column(db.String(50))
    rfile_pdf1 = db.Column(db.String(50))
    rfile_exc2 = db.Column(db.String(50))
    rfile_pdf2 = db.Column(db.String(50))
    radate = db.Column(db.DateTime)
    rfile_new1 = db.Column(db.String(50))
    rfile_new2 = db.Column(db.String(50))
    rcno = db.Column(db.String(30))
    bmodid = db.Column(db.String(20))
    bmoddate = db.Column(db.DateTime)
    rfile_exc1_1 = db.Column(db.String(50))
    rfile_pdf1_1 = db.Column(db.String(50))
    rfile_exc1_2 = db.Column(db.String(50))
    rfile_pdf1_2 = db.Column(db.String(50))
    rfile_exc2_1 = db.Column(db.String(50))
    rfile_pdf2_1 = db.Column(db.String(50))
    rfile_exc2_2 = db.Column(db.String(50))
    rfile_pdf2_2 = db.Column(db.String(50))
    rfile_new1_1 = db.Column(db.String(50))
    rfile_new1_2 = db.Column(db.String(50))
    rfile_new2_1 = db.Column(db.String(50))
    rfile_new2_2 = db.Column(db.String(50))

class RoadCase(db.Model):
    __tablename__ = 'roadcase'

    rcid = db.Column(db.Integer, primary_key=True, autoincrement=True)
    rcstatus = db.Column(db.String(1), nullable=False)
    rcno = db.Column(db.String(30))
    rcname = db.Column(db.String(200))
    rconame = db.Column(db.String(100))
    rcotel = db.Column(db.String(20))
    rcsdate = db.Column(db.Date)
    rcedate = db.Column(db.Date)
    rcnote = db.Column(db.String(500))
    bmodid = db.Column(db.String(20))
    bmoddate = db.Column(db.DateTime)
    rrpttitle = db.Column(db.String(100))